added health check step to deploy workflow

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -50,6 +50,24 @@ jobs:
           deployment_id=$(aws deploy create-deployment --application-name ${{ vars.APPLICATION_NAME }} --deployment-group-name ${{ env.DEPLOYMENT_GROUP }} --github-location repository=$GITHUB_REPOSITORY,commitId=$GITHUB_SHA --ignore-application-stop-failures --query "deploymentId" --output text --no-paginate)
           echo deployment_id=$deployment_id >> "$GITHUB_OUTPUT"
 
-      - name: Wait and verify whether the deployment was successful
+      - name: Wait and verify whether the CodeDeploy deployment was successful
         run: |
           aws deploy wait deployment-successful --deployment-id ${{ steps.codedeploy.outputs.deployment_id }}
+
+      - name: App server health check
+        run: |
+          NUMBER_OF_ATTEMPTS=10
+          SLEEP_TIME=5
+          URL=http://lerkasan.net
+          for i in $(seq 1 $NUMBER_OF_ATTEMPTS);
+          do
+            HTTP_CODE=$(curl --insecure --write-out '%{http_code}' -o /dev/null -m 10 -q -s $URL)
+            if [ "$HTTP_CODE" == "200" ]; then
+              echo "App server is running."
+              exit 0
+            fi
+            echo "Attempt to curl endpoint returned HTTP Code $HTTP_CODE. Backing off and retrying."
+            sleep $SLEEP_TIME
+          done
+          echo "App server did not respond after expected time. Failing."
+          exit 1
